# Generated by Django 5.0.3 on 2024-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cbm',
            fields=[
                ('model_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cbm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cbm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsAvg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, db_column='ITEM', max_length=50, null=True)),
                ('avg_2022', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ms_avg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('model_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('number_275', models.IntegerField(blank=True, db_column='275', null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ms_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newtable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('jin_348_ms', models.IntegerField(blank=True, db_column='JIN#348-MS', null=True)),
                ('jin_349_ms', models.IntegerField(blank=True, db_column='JIN#349-MS', null=True)),
                ('jin_352_ms', models.IntegerField(blank=True, db_column='JIN#352-MS', null=True)),
                ('jin_353_ms', models.IntegerField(blank=True, db_column='JIN#353-MS', null=True)),
                ('jin_354_ms', models.IntegerField(blank=True, db_column='JIN#354-MS', null=True)),
                ('jin_355_ms', models.IntegerField(blank=True, db_column='JIN#355-MS', null=True)),
                ('jin_356_ms', models.IntegerField(blank=True, db_column='JIN#356-MS', null=True)),
                ('jin_357_ms', models.IntegerField(blank=True, db_column='JIN#357-MS', null=True)),
                ('jin_358_ms', models.IntegerField(blank=True, db_column='JIN#358-MS', null=True)),
                ('jin_359_ms', models.IntegerField(blank=True, db_column='JIN#359-MS', null=True)),
                ('jin_360_ms', models.IntegerField(blank=True, db_column='JIN#360-MS', null=True)),
                ('jin_361_ms', models.IntegerField(blank=True, db_column='JIN#361-MS', null=True)),
                ('jin_362_ms', models.IntegerField(blank=True, db_column='JIN#362-MS', null=True)),
                ('jin_363_ms', models.IntegerField(blank=True, db_column='JIN#363-MS', null=True)),
                ('jin_364_ms', models.IntegerField(blank=True, db_column='JIN#364-MS', null=True)),
                ('jin_365_ms', models.IntegerField(blank=True, db_column='JIN#365-MS', null=True)),
                ('jin_366_ms', models.IntegerField(blank=True, db_column='JIN#366-MS', null=True)),
                ('jin_373_ms', models.IntegerField(blank=True, db_column='JIN#373-MS', null=True)),
                ('jin_374_ms', models.IntegerField(blank=True, db_column='JIN#374-MS', null=True)),
                ('jin_375_ms', models.IntegerField(blank=True, db_column='JIN#375-MS', null=True)),
                ('jin_376_ms', models.IntegerField(blank=True, db_column='JIN#376-MS', null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.IntegerField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.IntegerField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.IntegerField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'ny_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
