# Generated by Django 5.0.3 on 2024-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
