# Generated by Django 5.0.3 on 2024-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_item_color_code_item_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
