# Generated by Django 5.0.3 on 2024-03-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_alter_item_color_code_alter_item_model_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='msavg',
            table='msavg',
        ),
    ]
